set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets clk_IBUF]
set_property PACKAGE_PIN R2 [get_ports clk ]
set_property PACKAGE_PIN T1 [get_ports rst ]
set_property PACKAGE_PIN U1 [get_ports rw ]
set_property PACKAGE_PIN V17 [get_ports din[0] ]
set_property PACKAGE_PIN V16 [get_ports din[1] ]
set_property PACKAGE_PIN W16 [get_ports din[2] ]
set_property PACKAGE_PIN W17 [get_ports din[3] ]
set_property PACKAGE_PIN U16 [get_ports dout[0] ]
set_property PACKAGE_PIN E19 [get_ports dout[1] ]
set_property PACKAGE_PIN U19 [get_ports dout[2] ]
set_property PACKAGE_PIN V19 [get_ports dout[3] ]

set_property IOSTANDARD LVCMOS33 [get_ports {clk}]
set_property IOSTANDARD LVCMOS33 [get_ports {rst}]
set_property IOSTANDARD LVCMOS33 [get_ports {rw}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
