set_property PACKAGE_PIN r2  [get_ports areg[3]]
set_property PACKAGE_PIN t1  [get_ports areg[2]]
set_property PACKAGE_PIN u1  [get_ports areg[1]]
set_property PACKAGE_PIN w2  [get_ports areg[0]]
set_property PACKAGE_PIN r3  [get_ports breg[3]]
set_property PACKAGE_PIN t2  [get_ports breg[2]]
set_property PACKAGE_PIN t3  [get_ports breg[1]]
set_property PACKAGE_PIN v2  [get_ports breg[0]]
set_property PACKAGE_PIN w13  [get_ports op[1]]
set_property PACKAGE_PIN w14  [get_ports op[0]]
set_property PACKAGE_PIN w15  [get_ports cin]
set_property PACKAGE_PIN v15  [get_ports al]
set_property PACKAGE_PIN u3 [get_ports dout[0]]
set_property PACKAGE_PIN p3 [get_ports dout[1]]
set_property PACKAGE_PIN n3 [get_ports dout[2]]
set_property PACKAGE_PIN p1 [get_ports dout[3]]
set_property PACKAGE_PIN l1 [get_ports cout]



set_property IOSTANDARD LVCMOS33 [get_ports {areg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {areg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {areg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {areg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {breg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {breg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {breg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {breg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {al}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cin}]
set_property IOSTANDARD LVCMOS33 [get_ports {cout}]