set_property PACKAGE_PIN R2 [get_ports areg[3]]
set_property PACKAGE_PIN T1 [get_ports areg[2]]
set_property PACKAGE_PIN U1 [get_ports areg[1]]
set_property PACKAGE_PIN W2 [get_ports areg[0]]

set_property PACKAGE_PIN R3 [get_ports breg[3]]
set_property PACKAGE_PIN T2 [get_ports breg[2]]
set_property PACKAGE_PIN T3 [get_ports breg[1]]
set_property PACKAGE_PIN V2 [get_ports breg[0]]

set_property PACKAGE_PIN V17 [get_ports cin]
set_property PACKAGE_PIN V16 [get_ports al]

set_property PACKAGE_PIN W17 [get_ports op[1]]
set_property PACKAGE_PIN W16 [get_ports op[0]]

set_property PACKAGE_PIN V19 [get_ports dout[3]]
set_property PACKAGE_PIN U19 [get_ports dout[2]]
set_property PACKAGE_PIN E19 [get_ports dout[1]]
set_property PACKAGE_PIN U16 [get_ports dout[0]]

set_property PACKAGE_PIN L1 [get_ports cout]

set_property IOSTANDARD LVCMOS33 [get_ports {areg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {areg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {areg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {areg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {breg[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {breg[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {breg[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {breg[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cin}]
set_property IOSTANDARD LVCMOS33 [get_ports {al}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {op[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cout}]
